#! /bin/sh

sxhkd &

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config focus_by_distance   true
#bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

# Base 16 colors
#bspc config normal_border_color "#2b303b"
#bspc config focused_border_color_a "#65737e"
#bspc config focused_border_color "#32393f"

# Dark Gray colors
bspc config normal_border_color "#1f1f1f"
bspc config focused_border_color "#1f1f1f"


bspc rule -a VirtualBox desktop=^6 follow=on
bspc rule -a jetbrains-pycharm desktop=^2 follow=on
bspc rule -a mpv desktop=^3 follow=on


if [ $(bspc query -M | wc -l) -eq 2 ]; then
  bspc monitor LVDS-0 -d 6 7 8 9 10
  bspc monitor DP-3 -d 1 2 3 4 5
else
  bspc monitor -d a b c d e f
fi

panel &
compton -b &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#nitrogen --restore &
sh ~/.fehbg &
